#!/bin/sh
#
# Borrowed from meta-mentor [May 6th, 2022 akuster]
#
# Copyright 2007-2021 Siemens Digital Industries Software
#
# This file is licensed under the terms of the GNU General Public License
# version 2.  This program  is licensed "as is" without any warranty of any
# kind, whether express or implied.

echo "Verifying access to sudo, please enter your password if prompted."
if [ "$(id -u)" -ne 0 ]; then
    SUDO=sudo
    $SUDO -v
    if [ $? -ne 0 ]; then
        echo >&2 "Could not use sudo, exiting"
        exit 1
    fi
else
    SUDO=
fi

PKGS="gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev zstd liblz4-tool"

echo "Installing packages required to build Yocto Summit hands-on"
$SUDO apt-get update
$SUDO apt-get -y install $PKGS

echo "Generating the en_US.UTF-8 locale"
$SUDO locale-gen en_US.UTF-8

echo "Setup complete"
